#!/usr/bin/env python3
"""
Build script: reads all Markdown files and generates data/content.js
Usage: python3 build_content.py
"""
import os
import json
import re
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

CHAPTER_DIRS = [
    ('01', '01-投资认知建立', '第一阶段：投资认知建立'),
    ('02', '02-股票基础', '第二阶段：股票基础'),
    ('03', '03-基金基础', '第三阶段：基金基础'),
    ('04', '04-财报分析', '第四阶段：财报分析'),
    ('05', '05-估值体系', '第五阶段：估值体系'),
    ('06', '06-基金投资体系', '第六阶段：基金投资体系'),
    ('07', '07-技术分析', '第七阶段：技术分析'),
    ('08', '08-量化投资', '第八阶段：量化投资'),
    ('09', '09-构建个人投资系统', '第九阶段：构建个人投资系统'),
]


def escape_js_string(s):
    """Escape a string for embedding in a JS template literal"""
    return s.replace('\\', '\\\\').replace('`', '\\`').replace('$', '\\$')


def find_md_files(chapter_dir):
    """Find all .md files in a chapter directory, sorted"""
    path = os.path.join(BASE_DIR, '..', chapter_dir)
    if not os.path.isdir(path):
        return []
    files = sorted([f for f in os.listdir(path) if f.endswith('.md')])
    return files


def find_py_files(chapter_dir):
    """Find all .py files in a chapter directory, sorted"""
    path = os.path.join(BASE_DIR, '..', chapter_dir)
    if not os.path.isdir(path):
        return []
    files = sorted([f for f in os.listdir(path) if f.endswith('.py')])
    return files


def find_png_files(chapter_dir):
    """Find all .png files in a chapter directory, sorted"""
    path = os.path.join(BASE_DIR, '..', chapter_dir)
    if not os.path.isdir(path):
        return []
    files = sorted([f for f in os.listdir(path) if f.endswith('.png')])
    return files


def build_toc(chapters_data):
    """Build table of contents from chapters"""
    toc = []
    for ch in chapters_data:
        chapter_entry = {
            'id': ch['id'],
            'title': ch['title'],
            'sections': []
        }
        for sec in ch['sections']:
            section_entry = {
                'id': sec['id'],
                'title': sec['title'],
                'file': sec['file'],
                'headings': []
            }
            # Extract H2/H3 headings from markdown
            content = sec['raw_content']
            for line in content.split('\n'):
                line = line.strip()
                if line.startswith('## ') and not line.startswith('### '):
                    h_text = line[3:].strip()
                    h_id = re.sub(r'[^\w一-鿿]+', '-', h_text).strip('-').lower()
                    section_entry['headings'].append({'level': 2, 'text': h_text, 'id': h_id})
                elif line.startswith('### '):
                    h_text = line[4:].strip()
                    h_id = re.sub(r'[^\w一-鿿]+', '-', h_text).strip('-').lower()
                    section_entry['headings'].append({'level': 3, 'text': h_text, 'id': h_id})
            chapter_entry['sections'].append(section_entry)
        toc.append(chapter_entry)
    return toc


def main():
    chapters_data = []

    for ch_id, ch_dir, ch_title in CHAPTER_DIRS:
        md_files = find_md_files(ch_dir)
        py_files = find_py_files(ch_dir)
        png_files = find_png_files(ch_dir)

        if not md_files:
            continue

        sections = []
        for mf in md_files:
            filepath = os.path.join(BASE_DIR, '..', ch_dir, mf)
            with open(filepath, 'r', encoding='utf-8') as f:
                raw = f.read()

            # Derive section title from filename (remove leading number and extension)
            section_title = re.sub(r'^\d+-?', '', mf).replace('.md', '')
            section_title = section_title.strip()

            sections.append({
                'id': f'sec-{ch_id}-{mf.replace(".md", "")}',
                'title': section_title,
                'file': mf,
                'raw_content': raw,
                'py_files': [pf for pf in py_files],
                'png_files': [pf for pf in png_files],
                'chapter_dir': ch_dir,
            })

        chapters_data.append({
            'id': f'ch-{ch_id}',
            'title': ch_title,
            'dir': ch_dir,
            'sections': sections,
            'py_files': py_files,
            'png_files': png_files,
        })

    toc = build_toc(chapters_data)

    # ---- Generate content.js ----
    js_lines = []
    js_lines.append('// Auto-generated by build_content.py. DO NOT EDIT.')
    js_lines.append('// Contains all course content as raw markdown for client-side rendering.')
    js_lines.append('')
    js_lines.append('var COURSE_TOC = ' + json.dumps(toc, ensure_ascii=False, indent=2) + ';')
    js_lines.append('')
    js_lines.append('var COURSE_CONTENT = {')

    for ch in chapters_data:
        for sec in ch['sections']:
            escaped = escape_js_string(sec['raw_content'])
            js_lines.append(f'  "{sec["id"]}": {{')
            js_lines.append(f'    chapterId: "{ch["id"]}",')
            js_lines.append(f'    chapterTitle: {json.dumps(ch["title"], ensure_ascii=False)},')
            js_lines.append(f'    sectionTitle: {json.dumps(sec["title"], ensure_ascii=False)},')
            js_lines.append(f'    chapterDir: "{sec["chapter_dir"]}",')
            js_lines.append(f'    pyFiles: {json.dumps(sec["py_files"], ensure_ascii=False)},')
            js_lines.append(f'    pngFiles: {json.dumps(sec["png_files"], ensure_ascii=False)},')
            js_lines.append(f'    markdown: `{escaped}`')
            js_lines.append(f'  }},')

    js_lines.append('};')

    output_path = os.path.join(BASE_DIR, 'data', 'content.js')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(js_lines))

    print(f'Generated {output_path}')
    print(f'  Chapters: {len(toc)}')
    total_sections = sum(len(ch['sections']) for ch in chapters_data)
    print(f'  Sections: {total_sections}')
    total_headings = sum(len(sec['headings']) for ch in toc for sec in ch['sections'])
    print(f'  Headings: {total_headings}')

    size_kb = os.path.getsize(output_path) / 1024
    print(f'  File size: {size_kb:.1f} KB')


if __name__ == '__main__':
    main()
